# -*- coding: utf-8 -*-
"""M4_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17I57IB-pMy65JPwX4tHyfo1Foqw9Zycy
"""


"""# **Librerias**"""

import agentpy as ap
import numpy as np
import heapq
import json
import random
from collections import deque

"""# **Constantes**"""

# Tamaño Entorno
WIDTH, HEIGHT = 450, 300

# Estados AGVs
AGV_IDLE = 'IDLE'
AGV_MOVING_TO_PALLET = 'MOVING_TO_PALLET'
AGV_TRANSPORTING = 'TRANSPORTING'
AGV_CHARGING = 'CHARGING'

# Estados Pallets
P_STORED = 'ALMACENADO'
P_RESERVED = 'RESERVADO'
P_BEING_TRANSPORTED = 'SIENDO_TRANSPORTADO'
P_DELIVERED = 'ENTREGADO'

# Estados Misiones
MISSION_PENDING = 'PENDIENTE'
MISSION_ASSIGNED = 'ASIGNADA'
MISSION_COMPLETED = 'COMPLETADA'

# Limites de Bateria
LOW_BATTERY_THRESHOLD = 30.0
CHARGED_BATTERY_THRESHOLD = 80.0

# Distancia minima entre AGVs
AGV_SAFETY_RADIUS = 32

# Que tan seguido se graba una frame para animar
FRAME_SAMPLE = 3

# Pasos cuando dos AGVs estan bloqueados antes de forzar un desvio
DEADLOCK_THRESHOLD = 4

# Si el path de un AGV (por maniobras locales acumuladas, ver
# `_resolve_deadlock`) supera esta longitud, se descarta y se re-planea
# de cero en vez de seguir insertando desvios locales sobre un path ya
# demasiado largo (evita que un AGV quede "atorado" indefinidamente).
MAX_DETOUR_PATH_LEN = 40

# Intentos de desvio local seguidos que pueden fallar antes de rendirse y
# re-planear de cero con BFS puro (ver `_resolve_deadlock` / failed_resolve_streak).
MAX_FAILED_RESOLVE_STREAK = 6

# Cuanto se queda en verde la mision completada en el panel antes de desaparecer
MISSION_COMPLETED_DISPLAY_STEPS = 10

# Estados Estaciones
STATION_AVAILABLE = "AVAILABLE"
STATION_RESERVED = "RESERVED"
STATION_OCCUPIED = "OCCUPIED"
STATION_OUT_OF_SERVICE = "OUT_OF_SERVICE"

# Flujos logisticos
FLOW_1_INTERVAL = 60   # Linea de produccion -> Rack o Caja de salida
FLOW_2_INTERVAL = 90   # Rack -> Caja de camion de salida
FLOW_3_INTERVAL = 120   # Caja de camion de entrada -> Rack
DOCK_DEPARTURE_INTERVAL = 30  # cada cuanto un camion recoge un pallet listo en un dock y lo libera

# Probabilidades de destino de flujo 1
P_DEST_RACK = 0.60
P_DEST_DOCK = 0.40

# --- M4: Estrategias de negociacion de misiones ---
# BASELINE: el AGV mas cercano al pallet gana (con ligero desempate por bateria).
# PROPOSED: heuristica de utilidad que ademas balancea carga de trabajo y evita
# mandar AGVs hacia zonas ya congestionadas por otros AGVs.
STRATEGY_BASELINE = "baseline"
STRATEGY_PROPOSED = "proposed"

# Pesos de U_{i,m} = -w_d*D_{i,m} + w_b*B_i - w_l*L_i - w_c*C_i
W_DISTANCE = 1.0     # penaliza distancia al pallet (misma escala que el baseline)
W_BATTERY = 0.3      # premia bateria alta (preferir AGVs mas cargados)
W_WORKLOAD = 15.0    # penaliza AGVs que ya han completado mas misiones (fairness)
W_CONGESTION = 25.0  # penaliza AGVs cercanos a otros AGVs activos junto al origen
CONGESTION_RADIUS = 40.0  # radio (unidades de mundo) para contar AGVs cercanos

# --- M4: Eventos dinamicos (requeridos por el reto, seccion 11) ---
# Peatones: obstaculos moviles temporales sobre las rutas de los AGVs
PEDESTRIAN_INTERVAL = 70   # cada cuanto puede aparecer un peaton nuevo
PEDESTRIAN_DURATION = 25   # pasos que el peaton permanece bloqueando esa zona
PEDESTRIAN_RADIUS = 12     # radio de bloqueo alrededor del peaton

# Estaciones en alarma / fuera de servicio temporalmente
STATION_ALARM_INTERVAL = 150  # cada cuanto se intenta poner una estacion en alarma
STATION_ALARM_DURATION = 40   # pasos que la estacion permanece fuera de servicio

# --- M4-EXT: Ruteo consciente de congestion (A*) ---
# BFS_ROUTING: BFS ciego (M4 original), solo evita racks.
# ASTAR_ROUTING: A* que ademas penaliza pasar cerca de otros AGVs EN MOVIMIENTO
# (MOVING_TO_PALLET/TRANSPORTING), para planear un desvio desde el inicio en
# vez de descubrir el choque a medio camino (ver `_resolve_deadlock`).
ROUTING_BFS = "bfs"
ROUTING_ASTAR = "astar_congestion"

ASTAR_CONGESTION_RADIUS_CELLS = 3  # radio (en celdas de CELL_SIZE) alrededor de otro AGV que se penaliza
ASTAR_CONGESTION_COST = 1.5        # costo extra por celda dentro de ese radio (vs 1.0 de una celda libre)

"""# **Entorno**"""

def make_zone(name, x, y, width, height, color):
    return {"name": name, "x": x, "y": y, "width": width, "height": height, "color": color}

zones_custom = [
    # Production Lines
    make_zone("Prod Line 1", 0, 225, 45, 15, "cornflowerblue"),
    make_zone("Prod Line 2", 0, 200, 45, 15, "cornflowerblue"),
    make_zone("Prod Line 3", 0, 175, 45, 15, "cornflowerblue"),
    make_zone("Prod Line 4", 0, 150, 45, 15, "cornflowerblue"),
    # Racks
    make_zone("Rack A", 150, 200, 100, 22, "sandybrown"),
    make_zone("Rack B", 150, 100, 100, 22, "sandybrown"),
    make_zone("Rack C", 200, 278, 100, 22, "sandybrown"),
    make_zone("Rack D", 300, 111, 22, 100, "sandybrown"),
    make_zone("Rack E", 200, 0, 100, 22, "sandybrown"),
    # Truck Docks
    make_zone("Dock 1", 425, 225, 20, 30, "yellowgreen"),
    make_zone("Dock 2", 425, 185, 20, 30, "yellowgreen"),
    make_zone("Dock 3", 425, 145, 20, 30, "yellowgreen"),
    make_zone("Dock 4", 425, 105, 20, 30, "yellowgreen")
]

# Estaciones de Carga
chargers_custom = [
    {"name": "Charger 1", "pos": (100, 275), "occupied_by": None},
    {"name": "Charger 2", "pos": (375, 275), "occupied_by": None}
]

CELL_SIZE = 5
GRID_W = WIDTH // CELL_SIZE
GRID_H = HEIGHT // CELL_SIZE

def world_to_grid(pos):
    gx = int(np.clip(pos[0] // CELL_SIZE, 0, GRID_W - 1))
    gy = int(np.clip(pos[1] // CELL_SIZE, 0, GRID_H - 1))
    return (gx, gy)

def grid_to_world(grid_pos):
    return np.array([grid_pos[0] * CELL_SIZE + CELL_SIZE / 2,
                     grid_pos[1] * CELL_SIZE + CELL_SIZE / 2], dtype=float)

AGV_DIAMETER = 26
AGV_CLEARANCE = 17
SERVICE_MARGIN = AGV_CLEARANCE + CELL_SIZE
NAV_RIGHT = 425  # pared del cuarto en el plano de los portones

def build_occupancy_grid(zones):
    # Centros transitables: el cuerpo completo debe caber fuera de zonas y paredes.
    xs = (np.arange(GRID_W) + 0.5) * CELL_SIZE
    ys = (np.arange(GRID_H) + 0.5) * CELL_SIZE
    xx, yy = np.meshgrid(xs, ys)
    blocked = ((xx < AGV_CLEARANCE) | (xx > NAV_RIGHT - AGV_CLEARANCE)
               | (yy < AGV_CLEARANCE) | (yy > HEIGHT - AGV_CLEARANCE))
    for z in zones:
        blocked |= ((xx > z["x"] - AGV_CLEARANCE)
                    & (xx < z["x"] + z["width"] + AGV_CLEARANCE)
                    & (yy > z["y"] - AGV_CLEARANCE)
                    & (yy < z["y"] + z["height"] + AGV_CLEARANCE))
    return blocked.astype(int)

NAV_GRID = build_occupancy_grid(zones_custom)

def segment_clear_of_obstacles(start, end, clearance=AGV_CLEARANCE):
    """Comprueba el segmento completo, no solo su celda de destino."""
    for pos in (start, end):
        if not (clearance <= pos[0] <= NAV_RIGHT - clearance
                and clearance <= pos[1] <= HEIGHT - clearance):
            return False
    for zone in zones_custom:
        enter, leave = 0.0, 1.0
        for axis, key, size in ((0, "x", "width"), (1, "y", "height")):
            low = zone[key] - clearance
            high = zone[key] + zone[size] + clearance
            delta = end[axis] - start[axis]
            if abs(delta) < 1e-9:
                if start[axis] <= low or start[axis] >= high:
                    break
            else:
                a, b = sorted(((low - start[axis]) / delta, (high - start[axis]) / delta))
                enter, leave = max(enter, a), min(leave, b)
                if enter >= leave:
                    break
        else:
            if enter < leave:
                return False
    return True

ENERGY_PER_UNIT = 0.035
ENERGY_RESERVE = 5.0
CHARGER_TREES = {}

def charger_route(position, charger):
    """Ruta mínima estática real, reutilizando un árbol BFS por cargador."""
    target = np.array(charger["pos"], dtype=float)
    goal = world_to_grid(target)
    if goal not in CHARGER_TREES:
        tree = {goal: None}
        queue = deque([goal])
        while queue:
            cell = queue.popleft()
            for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):
                neighbor = cell[0]+dx, cell[1]+dy
                x, y = neighbor
                if 0 <= x < GRID_W and 0 <= y < GRID_H and NAV_GRID[y,x] == 0 and neighbor not in tree:
                    tree[neighbor] = cell
                    queue.append(neighbor)
        CHARGER_TREES[goal] = tree
    tree = CHARGER_TREES[goal]
    cell = world_to_grid(position)
    if cell not in tree:
        return None
    route = []
    while cell is not None:
        route.append(grid_to_world(cell))
        cell = tree[cell]
    route.append(target)
    return route

def route_energy(position, route):
    if route is None:
        return float("inf")
    points = [position] + route
    return sum(float(np.linalg.norm(b-a)) for a,b in zip(points, points[1:])) * ENERGY_PER_UNIT


def zone_by_name(name):
    return next(z for z in zones_custom if z["name"] == name)

def edge_point(zone, side, margin=SERVICE_MARGIN):
    x, y, w, h = zone["x"], zone["y"], zone["width"], zone["height"]
    if side == "west":
        return (x - margin, y + h / 2)
    if side == "east":
        return (x + w + margin, y + h / 2)
    if side == "south":
        return (x + w / 2, y - margin)
    if side == "north":
        return (x + w / 2, y + h + margin)
    raise ValueError(side)

# Lado de cada rack que da hacia el pasillo abierto (para que los pallets
# aparezcan pegados a una orilla, no flotando en medio del pasillo)
RACK_SIDES = {
    "Rack A": "south",
    "Rack B": "north",
    "Rack C": "south",
    "Rack D": "west",
    "Rack E": "north",
}

DOCK_NAMES = ["Dock 1", "Dock 2", "Dock 3", "Dock 4"]

# Definicion de cada estacion con su punto accesible
STATION_DEFINITIONS = (
    [{"name": n, "kind": "RACK", "pos": edge_point(zone_by_name(n), s)} for n, s in RACK_SIDES.items()] +
    [{"name": n, "kind": "DOCK", "pos": edge_point(zone_by_name(n), "west")} for n in DOCK_NAMES]
)


class StationAgent(ap.Agent):

    def setup(self):
        self.station_id = None
        self.kind = None
        self.pos = np.array([0.0, 0.0])
        self.state = STATION_AVAILABLE
        self.current_pallet_id = None

    def is_available(self):
        return self.state == STATION_AVAILABLE

    def reserve(self, pallet_id):
        # La estacion es el destino de una mision en camino
        self.state = STATION_RESERVED
        self.current_pallet_id = pallet_id

    def occupy(self, pallet_id):
        # El pallet ya esta fisicamente en la estacion (llego o fue generado ahi)
        self.state = STATION_OCCUPIED
        self.current_pallet_id = pallet_id

    def release(self):
        # El pallet salio de la estacion y vuelve a estar libre.
        self.state = STATION_AVAILABLE
        self.current_pallet_id = None

    def set_out_of_service(self):
        self.state = STATION_OUT_OF_SERVICE

    def restore_service(self):
        self.state = STATION_AVAILABLE


class ProductionLine:

    def __init__(self, outlet_positions):
        self.outlets = [{"pos": np.array(p, dtype=float), "pallet_id": None} for p in outlet_positions]

    def free_outlets(self):
        return [o for o in self.outlets if o["pallet_id"] is None]

    def occupy_outlet(self, outlet, pallet_id):
        outlet["pallet_id"] = pallet_id

    def release_by_pallet(self, pallet_id):
        for o in self.outlets:
            if o["pallet_id"] == pallet_id:
                o["pallet_id"] = None

def find_path_grid(start_pos, goal_pos, grid):
    start = world_to_grid(start_pos)
    goal = world_to_grid(goal_pos)

    if start == goal:
        return [np.array(goal_pos, dtype=float)]

    queue = deque([start])
    came_from = {start: None}
    directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
    found = False

    while queue:
        current = queue.popleft()
        if current == goal:
            found = True
            break

        for dx, dy in directions:
            neighbor = (current[0] + dx, current[1] + dy)
            nx, ny = neighbor

            if 0 <= nx < GRID_W and 0 <= ny < GRID_H:
                if (grid[ny, nx] == 0 or neighbor == goal) and neighbor not in came_from:
                    came_from[neighbor] = current
                    queue.append(neighbor)

    if not found:
        return [np.array(goal_pos, dtype=float)]

    path = []
    curr = goal
    while curr is not None:
        path.append(grid_to_world(curr))
        curr = came_from[curr]
    path.reverse()
    path[-1] = np.array(goal_pos, dtype=float)
    return path


def find_path_astar_congestion(start_pos, goal_pos, grid, busy_cells,
                                radius=ASTAR_CONGESTION_RADIUS_CELLS,
                                cost=ASTAR_CONGESTION_COST):
    """A* con costo extra por celda cercana a un AGV en movimiento (busy_cells,
    en coordenadas de rejilla). Con busy_cells vacio, produce el mismo camino
    minimo que `find_path_grid` (BFS), solo que via A*."""
    start = world_to_grid(start_pos)
    goal = world_to_grid(goal_pos)
    if start == goal:
        return [np.array(goal_pos, dtype=float)]

    busy = busy_cells - {start}

    def extra_cost(cell):
        if not busy:
            return 0.0
        cx, cy = cell
        return sum(cost for bx, by in busy if abs(cx - bx) + abs(cy - by) <= radius)

    directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
    open_heap = [(0.0, start)]
    g_score = {start: 0.0}
    came_from = {start: None}
    closed = set()

    while open_heap:
        _, current = heapq.heappop(open_heap)
        if current in closed:
            continue
        closed.add(current)
        if current == goal:
            break
        cx, cy = current
        for dx, dy in directions:
            neighbor = (cx + dx, cy + dy)
            nx, ny = neighbor
            if 0 <= nx < GRID_W and 0 <= ny < GRID_H:
                if grid[ny, nx] == 0 or neighbor == goal:
                    step_cost = 1.0 + extra_cost(neighbor)
                    tentative = g_score[current] + step_cost
                    if neighbor not in g_score or tentative < g_score[neighbor] - 1e-9:
                        g_score[neighbor] = tentative
                        came_from[neighbor] = current
                        h = abs(goal[0] - nx) + abs(goal[1] - ny)
                        heapq.heappush(open_heap, (tentative + h, neighbor))

    if goal not in came_from:
        return [np.array(goal_pos, dtype=float)]

    path = []
    curr = goal
    while curr is not None:
        path.append(grid_to_world(curr))
        curr = came_from[curr]
    path.reverse()
    path[-1] = np.array(goal_pos, dtype=float)
    return path


# AGVs cuyo movimiento efectivamente ocupa un pasillo (un AGV IDLE o CHARGING
# esta parado, no compite por espacio de ruta con nadie)
ROUTING_BUSY_STATES = (AGV_MOVING_TO_PALLET, AGV_TRANSPORTING)


def plan_path(agv, target_pos):
    """Punto unico donde se decide como planear una ruta: BFS (M4 original)
    o A* con penalizacion por congestion (M4-EXT), segun `model.p.routing`.

    La congestion se lee de `model._routing_busy_cells`, una FOTO tomada una
    sola vez al inicio de cada `step()` (ver `DistributionCenter.step`), no
    las posiciones en vivo de `self.agvs`. Sin la foto, dos llamadas a
    `plan_path` dentro del mismo step (p.ej. un AGV que ya se movio este step
    vs uno que no) verian una mezcla inconsistente de posiciones "de este
    step" y "del step anterior", lo que en la practica generaba MAS
    conflictos de ruta en vez de menos."""
    routing_mode = getattr(agv.model.p, "routing", ROUTING_BFS)
    if routing_mode == ROUTING_ASTAR:
        busy_cells = getattr(agv.model, "_routing_busy_cells", set()) - {world_to_grid(agv.pos)}
        return find_path_astar_congestion(agv.pos, target_pos, NAV_GRID, busy_cells)
    return find_path_grid(agv.pos, target_pos, NAV_GRID)

"""# **Pallet, Mission y MissionManager**"""

class Pallet:
    def __init__(self, p_id, pos):
        self.id = p_id
        self.pos = np.array(pos, dtype=float)
        self.state = P_STORED

class Mission:
    def __init__(self, m_id, p_id, origin, destination, origin_station_id=None, dest_station_id=None, created_at=None):
        self.id = m_id
        self.pallet_id = p_id
        self.origin = np.array(origin, dtype=float)
        self.destination = np.array(destination, dtype=float)
        self.status = MISSION_PENDING
        self.assigned_to = None
        self.origin_station_id = origin_station_id
        self.dest_station_id = dest_station_id
        self.created_at = created_at
        self.started_at = None
        self.completed_at = None

class MissionManager:
    """Tablon de anuncios de misiones: SOLO publica misiones y reune las pujas
    que cada AGV calcula por su cuenta. No compara AGVs ni decide quien gana
    (esa decision la toma cada AGVAgent con `determine_if_winner`, ver mas abajo),
    para no convertirse en un controlador centralizado."""

    def __init__(self, missions):
        self.missions = {m.id: m for m in missions}
        self.log = []
        self._published = set()

    def publish_mission(self, mission):
        if mission.id not in self._published:
            self.log.append(f"\n[SUBASTA] Misión {mission.id} publicada (Pallet: {mission.pallet_id})")
            self._published.add(mission.id)

    def collect_bids(self, mission, agv_list):
        bids = {}
        for agv in agv_list:
            bid = agv.evaluate_mission(mission)
            if bid is not None:
                self.log.append(f"  > {agv.agv_id} puja: {bid:.2f}")
                bids[agv.agv_id] = bid
            else:
                self.log.append(f"  > {agv.agv_id} no disponible (Estado: {agv.state}, Bat: {agv.battery:.1f}%)")
        return bids

"""# **Modelo Agente**"""

class AGVAgent(ap.Agent):
    def setup(self):
        self.agv_id = f"AGV-{self.id}"
        self.pos = np.array([0.0, 0.0], dtype=float)
        self.state = AGV_IDLE
        self.battery = 100.0
        self.speed = 5.0
        self.current_mission = None
        self.distance_traveled = 0.0
        self.completed_missions_count = 0
        self.stuck_steps = 0
        self.failed_resolve_streak = 0  # a diferencia de stuck_steps, NO se resetea tras un intento fallido de _resolve_deadlock
        self.path = []
        self.charger = None
        self.suspended_state = AGV_IDLE
        self.charge_phase = ""

        # --- M4: metricas por AGV ---
        self.active_steps = 0     # pasos moviendose hacia un pallet o transportando
        self.charging_steps = 0   # pasos en estacion de carga
        self.idle_steps = 0       # pasos sin mision ni carga
        self.charging_events = 0  # veces que fue a recargar

    def evaluate_mission(self, mission):
        # Si está ocupado o con batería baja, no participa en subastas
        if self.state != AGV_IDLE or self.battery <= LOW_BATTERY_THRESHOLD:
            return None
        strategy = getattr(self.model.p, "strategy", STRATEGY_BASELINE)
        if strategy == STRATEGY_PROPOSED:
            return self._utility_proposed(mission)
        return self._utility_baseline(mission)

    def _distance_to(self, point):
        return np.abs(self.pos[0] - point[0]) + np.abs(self.pos[1] - point[1])

    def _utility_baseline(self, mission):
        # BASELINE: AGV mas cercano al pallet gana, con ligero desempate por bateria
        dist_to_pallet = self._distance_to(mission.origin)
        return - dist_to_pallet + (self.battery * 0.1)

    def _route_congestion(self, mission):
        # Cuenta AGVs activos (no IDLE) cerca del punto medio entre ESTE AGV y
        # el origen de la mision, como proxy de que SU camino hacia alla ya
        # esta ocupado. Debe depender de self.pos: si dependiera solo de la
        # posicion de la mision, todos los AGVs que pujan por la misma mision
        # verian el mismo valor y el termino nunca podria cambiar quien gana.
        midpoint = (self.pos + mission.origin) / 2.0
        return sum(
            1 for other in self.model.agvs
            if other.agv_id != self.agv_id and other.state != AGV_IDLE
            and np.linalg.norm(other.pos - midpoint) < CONGESTION_RADIUS
        )

    def _utility_proposed(self, mission):
        # PROPUESTA: U_{i,m} = -w_d*D_{i,m} + w_b*B_i - w_l*L_i - w_c*C_i
        dist_to_pallet = self._distance_to(mission.origin)
        workload = self.completed_missions_count
        congestion = self._route_congestion(mission)
        return (- W_DISTANCE * dist_to_pallet
                + W_BATTERY * self.battery
                - W_WORKLOAD * workload
                - W_CONGESTION * congestion)

    def determine_if_winner(self, bids):
        """Con el tablon de pujas ya publicado por el Mission Manager (todas
        las pujas son visibles para todos), cada AGV decide POR SI MISMO si
        fue quien ofrecio la mejor puja. En caso de empate, gana el agv_id
        menor (regla determinista que cualquier AGV puede evaluar de forma
        independiente, sin que el Mission Manager compare a nadie)."""
        if self.agv_id not in bids:
            return False
        best_bid = max(bids.values())
        tied = sorted(agv_id for agv_id, b in bids.items() if b == best_bid)
        return self.agv_id == tied[0]

    def accept_mission(self, mission):
        # El AGV acepta la mision para si mismo (auto-asignacion)
        self.current_mission = mission
        self.state = AGV_MOVING_TO_PALLET
        self.path = plan_path(self, mission.origin)

    def needs_recharge(self):
        if self.state == AGV_CHARGING:
            return False
        required = min(route_energy(self.pos, charger_route(self.pos, c)) for c in self.model.chargers)
        return self.battery <= max(LOW_BATTERY_THRESHOLD, required + ENERGY_RESERVE + self.speed * ENERGY_PER_UNIT)

    def go_to_recharge(self, chargers):
        if self.state != AGV_CHARGING:
            self.suspended_state = self.state
            self.state = AGV_CHARGING
            self.path = []
        options = []
        for charger in chargers:
            if charger["occupied_by"] not in (None, self.agv_id):
                continue
            route = charger_route(self.pos, charger)
            energy = route_energy(self.pos, route)
            if energy + 1.0 < self.battery:
                options.append((energy, charger, route))
        if not options:
            self.charge_phase = "WAITING"
            return False
        _, closest, route = min(options, key=lambda option: option[0])
        closest["occupied_by"] = self.agv_id
        self.charger = closest
        self.charging_events += 1
        self.charge_phase = "TO_CHARGER"
        self.path = route
        return True

    def peek_next_position(self):
        if not self.path:
            return self.pos.copy()
        target = self.path[0]
        dir_vec = target - self.pos
        dist = np.linalg.norm(dir_vec)
        if dist <= self.speed or dist < 1e-3:
            return target.copy()
        return self.pos + (dir_vec / dist) * self.speed

    def follow_path(self):
        if not self.path:
            return

        target = self.path[0]
        dir_vec = target - self.pos
        dist = np.linalg.norm(dir_vec)

        if dist <= self.speed or dist < 1e-3:
            self.pos = target.copy()
            self.path.pop(0)
            step_dist = dist
        else:
            step_vector = (dir_vec / dist) * self.speed
            self.pos += step_vector
            step_dist = self.speed

        self.distance_traveled += step_dist
        self.battery = max(0.0, self.battery - (step_dist * ENERGY_PER_UNIT))

"""# **Modelo Multiagente**"""

class DistributionCenter(ap.Model):
    def setup(self):
        self.agvs = ap.AgentList(self, self.p.n_agvs, AGVAgent)
        pos_ini = [(80, 50), (80, 120), (80, 180), (80, 240)]
        for i, agv in enumerate(self.agvs):
            agv.pos = np.array(pos_ini[i % len(pos_ini)], dtype=float)

        self.production_line = ProductionLine([(45 + SERVICE_MARGIN, y) for y in (232.5, 207.5, 182.5, 157.5)])

        self.chargers = [dict(c, occupied_by=None) for c in chargers_custom]

        self.stations = ap.AgentList(self, len(STATION_DEFINITIONS), StationAgent)
        for station, definition in zip(self.stations, STATION_DEFINITIONS):
            station.station_id = definition["name"]
            station.kind = definition["kind"]
            station.pos = np.array(definition["pos"], dtype=float)
        self.stations_by_name = {s.station_id: s for s in self.stations}

        self.mission_manager = MissionManager([])
        self.pallets = {}
        self.mission_counter = 1
        self.pallet_counter = 1
        self.total_completed = 0
        self.reassignments = 0
        self.history = []

        # Ultimo paso en que cada flujo genero mision
        self.last_flow1_t = -FLOW_1_INTERVAL
        self.last_flow2_t = -FLOW_2_INTERVAL
        self.last_flow3_t = -FLOW_3_INTERVAL
        self.last_departure_t = -DOCK_DEPARTURE_INTERVAL

        # --- M4: eventos dinamicos ---
        self.pedestrians = []  # [{"pos": np.array, "until": t}]
        self.last_pedestrian_t = -PEDESTRIAN_INTERVAL
        self.station_alarms = {}  # {station_id: t_restauracion}
        self.last_alarm_t = -STATION_ALARM_INTERVAL

        self._record_frame()

    def spawn_pedestrian(self):
        gx, gy = np.random.randint(0, GRID_W), np.random.randint(0, GRID_H)
        tries = 0
        while NAV_GRID[gy, gx] == 1 and tries < 10:
            gx, gy = np.random.randint(0, GRID_W), np.random.randint(0, GRID_H)
            tries += 1
        pos = grid_to_world((gx, gy))
        self.pedestrians.append({"pos": pos, "until": self.t + PEDESTRIAN_DURATION})
        self.mission_manager.log.append(f"[EVENTO] Peatón cruza cerca de ({pos[0]:.0f}, {pos[1]:.0f})")

    def update_pedestrians(self):
        if self.t - self.last_pedestrian_t >= PEDESTRIAN_INTERVAL:
            self.spawn_pedestrian()
            self.last_pedestrian_t = self.t
        self.pedestrians = [p for p in self.pedestrians if p["until"] > self.t]

    def update_station_alarms(self):
        for station_id, restore_t in list(self.station_alarms.items()):
            if self.t >= restore_t:
                self.stations_by_name[station_id].restore_service()
                self.mission_manager.log.append(f"[EVENTO] {station_id} vuelve a estar disponible")
                del self.station_alarms[station_id]

        if self.t - self.last_alarm_t >= STATION_ALARM_INTERVAL:
            candidates = [s for s in self.stations if s.is_available()]
            if candidates:
                station = candidates[np.random.randint(len(candidates))]
                station.set_out_of_service()
                self.station_alarms[station.station_id] = self.t + STATION_ALARM_DURATION
                self.mission_manager.log.append(f"[EVENTO] {station.station_id} entra en alarma / fuera de servicio")
            self.last_alarm_t = self.t


    def try_flow_1(self):
        # Flujo 1: Linea de produccion -> Rack o Caja de salida (60%/40%)
        free = self.production_line.free_outlets()
        if not free:
            return False  # sin salidas libres: no se genera, no se acumula

        outlet = free[np.random.randint(len(free))]

        dest_kind = "RACK" if np.random.random() < P_DEST_RACK else "DOCK"
        candidates = [s for s in self.stations if s.kind == dest_kind and s.is_available()]
        if not candidates:
            return False  # sin destino disponible: no se genera
        dest_station = candidates[np.random.randint(len(candidates))]

        pallet_id = f"P{self.pallet_counter}"
        self.pallet_counter += 1
        self.pallets[pallet_id] = Pallet(pallet_id, outlet["pos"])
        self.production_line.occupy_outlet(outlet, pallet_id)
        dest_station.reserve(pallet_id)

        m_id = f"M{self.mission_counter}"
        self.mission_counter += 1
        mission = Mission(m_id, pallet_id, outlet["pos"], dest_station.pos,
                           origin_station_id=None, dest_station_id=dest_station.station_id,
                           created_at=self.t)
        self.mission_manager.missions[m_id] = mission
        self.mission_manager.log.append(
            f"[FLUJO 1] {m_id}: Producción -> {dest_station.station_id} ({dest_kind}), pallet {pallet_id}"
        )
        return True

    def try_flow_2(self):
        # Flujo 2: Rack -> Caja de camión de salida
        origin_candidates = [s for s in self.stations if s.kind == "RACK" and s.state == STATION_OCCUPIED]
        if not origin_candidates:
            return False
        origin_station = origin_candidates[np.random.randint(len(origin_candidates))]

        dest_candidates = [s for s in self.stations if s.kind == "DOCK" and s.is_available()]
        if not dest_candidates:
            return False
        dest_station = dest_candidates[np.random.randint(len(dest_candidates))]

        pallet_id = origin_station.current_pallet_id
        dest_station.reserve(pallet_id)

        m_id = f"M{self.mission_counter}"
        self.mission_counter += 1
        mission = Mission(m_id, pallet_id, origin_station.pos, dest_station.pos,
                           origin_station_id=origin_station.station_id, dest_station_id=dest_station.station_id,
                           created_at=self.t)
        self.mission_manager.missions[m_id] = mission
        self.mission_manager.log.append(
            f"[FLUJO 2] {m_id}: {origin_station.station_id} -> {dest_station.station_id}, pallet {pallet_id}"
        )
        return True

    def try_flow_3(self):
        # Flujo 3: Caja de camión de entrada -> Rack
        origin_candidates = [s for s in self.stations if s.kind == "DOCK" and s.is_available()]
        if not origin_candidates:
            return False
        origin_station = origin_candidates[np.random.randint(len(origin_candidates))]

        dest_candidates = [s for s in self.stations if s.kind == "RACK" and s.is_available()]
        if not dest_candidates:
            return False
        dest_station = dest_candidates[np.random.randint(len(dest_candidates))]

        pallet_id = f"P{self.pallet_counter}"
        self.pallet_counter += 1
        self.pallets[pallet_id] = Pallet(pallet_id, origin_station.pos)
        origin_station.occupy(pallet_id)
        dest_station.reserve(pallet_id)

        m_id = f"M{self.mission_counter}"
        self.mission_counter += 1
        mission = Mission(m_id, pallet_id, origin_station.pos, dest_station.pos,
                           origin_station_id=origin_station.station_id, dest_station_id=dest_station.station_id,
                           created_at=self.t)
        self.mission_manager.missions[m_id] = mission
        self.mission_manager.log.append(
            f"[FLUJO 3] {m_id}: {origin_station.station_id} -> {dest_station.station_id}, pallet {pallet_id}"
        )
        return True

    def try_dock_departure(self):
        # Intentar vaciar uno de los docks
        occupied_docks = [s for s in self.stations if s.kind == "DOCK" and s.state == STATION_OCCUPIED]
        if not occupied_docks:
            return False
        dock = occupied_docks[np.random.randint(len(occupied_docks))]
        self.mission_manager.log.append(
            f"[DESPACHO] Camión recoge {dock.current_pallet_id} en {dock.station_id}, dock queda libre"
        )
        dock.release()
        return True

    def run_flow_generator(self):
        # Correr la revision y generacion de cada flujo. `flow_scale` es un
        # parametro opcional (default 1.0 = intervalos de referencia del reto
        # sin modificar) que permite correr un escenario experimental adicional
        # con mas o menos misiones por unidad de tiempo, sin tocar el escenario
        # de referencia por default.
        scale = getattr(self.p, "flow_scale", 1.0)
        f1, f2, f3 = FLOW_1_INTERVAL / scale, FLOW_2_INTERVAL / scale, FLOW_3_INTERVAL / scale
        if self.t - self.last_flow1_t >= f1:
            if self.try_flow_1():
                self.last_flow1_t = self.t
        if self.t - self.last_flow2_t >= f2:
            if self.try_flow_2():
                self.last_flow2_t = self.t
        if self.t - self.last_flow3_t >= f3:
            if self.try_flow_3():
                self.last_flow3_t = self.t
        if self.t - self.last_departure_t >= DOCK_DEPARTURE_INTERVAL:
            if self.try_dock_departure():
                self.last_departure_t = self.t

    def _record_frame(self):
        if self.t % FRAME_SAMPLE != 0:
            return
        self.history.append({
            "t": self.t,
            "agvs": [{"id": a.agv_id, "pos": a.pos.copy(), "battery": a.battery, "state": a.state} for a in self.agvs],
            "pallets": [{"id": p.id, "pos": p.pos.copy(), "state": p.state} for p in self.pallets.values()],
            "stations": [{"id": s.station_id, "state": s.state, "pallet": s.current_pallet_id} for s in self.stations],
            "missions": [{"id": m.id, "pallet": m.pallet_id, "status": m.status, "assigned": m.assigned_to}
                        for m in self.mission_manager.missions.values()
                        if m.status != MISSION_COMPLETED
                        or (m.completed_at is not None and self.t - m.completed_at < MISSION_COMPLETED_DISPLAY_STEPS)],
            "pedestrians": [{"pos": p["pos"].copy()} for p in self.pedestrians],
            "completed": self.total_completed
        })

    def _current_target(self, agv):
        """A donde se dirige el AGV en este momento, para poder re-planear
        la ruta completa desde cero (ver `_resolve_deadlock`)."""
        if agv.state == AGV_MOVING_TO_PALLET and agv.current_mission is not None:
            return agv.current_mission.origin
        if agv.state == AGV_TRANSPORTING and agv.current_mission is not None:
            return agv.current_mission.destination
        if agv.state == AGV_CHARGING and agv.charger is not None:
            return np.array(agv.charger["pos"], dtype=float)
        return None

    def _resolve_deadlock(self, agv, reserved):
        """Replanear alrededor de vehículos; si no hay paso, retroceder a una zona libre."""
        target = self._current_target(agv)
        if target is None:
            return False
        others = [pos for oid, pos in reserved.items() if oid != agv.agv_id]
        def clear(a, b):
            if not segment_clear_of_obstacles(a, b):
                return False
            delta = b - a
            length = float(np.dot(delta, delta))
            for pos in others:
                alpha = 0 if length < 1e-9 else float(np.clip(np.dot(pos-a, delta)/length, 0, 1))
                if np.linalg.norm(a + alpha*delta - pos) < AGV_SAFETY_RADIUS - 1e-6:
                    return False
            return True
        start = world_to_grid(agv.pos)
        goal = world_to_grid(target)
        queue = deque([start])
        parent = {start: None}
        found = None
        best = start
        best_score = -float("inf")
        while queue:
            cell = queue.popleft()
            point = agv.pos if cell == start else grid_to_world(cell)
            if cell == goal and clear(point, target):
                found = cell
                break
            distance = np.linalg.norm(point - agv.pos)
            if 20 <= distance <= 90:
                separation = min(np.linalg.norm(point - other) for other in others)
                score = min(separation, AGV_SAFETY_RADIUS * 2) - distance * 0.1
                if score > best_score:
                    best, best_score = cell, score
            for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):
                neighbor = (cell[0]+dx, cell[1]+dy)
                nx, ny = neighbor
                if not (0 <= nx < GRID_W and 0 <= ny < GRID_H) or neighbor in parent or NAV_GRID[ny,nx]:
                    continue
                if clear(point, grid_to_world(neighbor)):
                    parent[neighbor] = cell
                    queue.append(neighbor)
        destination = found if found is not None else best
        if destination == start:
            return False
        route = []
        cell = destination
        while cell != start:
            route.append(grid_to_world(cell))
            cell = parent[cell]
        route.reverse()
        if found is not None:
            route.append(np.array(target, dtype=float))
        else:
            # Conservar el destino de la misión; no confundir ceder el paso con entregar.
            route += find_path_grid(route[-1], target, NAV_GRID)[1:]
        if agv.state == AGV_CHARGING and route_energy(agv.pos, route) + 1.0 >= agv.battery:
            return False
        agv.path = route
        self.mission_manager.log.append(f"[MANIOBRA] {agv.agv_id} replantea con vehículos como obstáculos")
        return True

    def _move_with_collision_avoidance(self, agv, reserved):
        if not agv.path:
            agv.stuck_steps = 0
            return

        original_speed = agv.speed
        for fraction in (1.0, 0.5, 0.25):
            agv.speed = original_speed * fraction
            next_pos = agv.peek_next_position()
            blocked = not segment_clear_of_obstacles(agv.pos, next_pos)
            if agv.state == AGV_CHARGING and route_energy(agv.pos, agv.path) + 1.0 >= agv.battery:
                blocked = True
            for other_id, other_pos in reserved.items():
                if other_id == agv.agv_id:
                    continue
                if np.linalg.norm(next_pos - other_pos) < AGV_SAFETY_RADIUS:
                    blocked = True
                    break
            if not blocked:
                for ped in self.pedestrians:
                    if np.linalg.norm(next_pos - ped["pos"]) < PEDESTRIAN_RADIUS:
                        blocked = True
                        break
            if not blocked:
                agv.follow_path()
                agv.speed = original_speed
                agv.stuck_steps = 0
                agv.failed_resolve_streak = 0
                reserved[agv.agv_id] = agv.pos.copy()
                return

        agv.speed = original_speed
        agv.stuck_steps += 1

        if agv.stuck_steps >= DEADLOCK_THRESHOLD:
            resolved = self._resolve_deadlock(agv, reserved)
            agv.stuck_steps = 0
            agv.speed = original_speed
            # A diferencia de stuck_steps (que se resetea siempre), este contador
            # SOLO se resetea si el desvio funciono -- si no, sigue creciendo
            # aunque stuck_steps vuelva a 0, para que _resolve_deadlock sepa
            # cuantos intentos van fallando de verdad y pueda escalar en serio.
            agv.failed_resolve_streak = 0 if resolved else agv.failed_resolve_streak + 1

    def step(self):
        # Foto de posiciones de AGVs en movimiento, tomada UNA sola vez al
        # inicio del step (antes de que nadie se mueva este step). Todas las
        # llamadas a `plan_path` durante este step usan esta misma foto, para
        # que la nocion de "congestion" sea consistente en vez de una mezcla
        # de posiciones ya actualizadas y sin actualizar dentro del mismo step.
        self._routing_busy_cells = {
            world_to_grid(a.pos) for a in self.agvs if a.state in ROUTING_BUSY_STATES
        }

        # 1. Generación de misiones
        self.run_flow_generator()

        # 1b. Eventos dinamicos (peatones, alarmas de estacion)
        self.update_pedestrians()
        self.update_station_alarms()

        # Recargar tiene prioridad sobre aceptar o continuar una misión.
        for agv in self.agvs:
            if agv.needs_recharge():
                agv.go_to_recharge(self.chargers)

        # 2. Subasta de misiones pendientes: el Mission Manager solo publica
        # y reune las pujas (tablon de anuncios); cada AGV decide por si mismo
        # si gano, viendo el mismo tablon (`determine_if_winner`), y se
        # autoasigna la mision (`accept_mission`). El Mission Manager nunca
        # compara AGVs ni elige un ganador.
        for m in self.mission_manager.missions.values():
            if m.status == MISSION_PENDING:
                self.mission_manager.publish_mission(m)
                bids = self.mission_manager.collect_bids(m, self.agvs)
                if not bids:
                    continue
                for agv in self.agvs:
                    if agv.determine_if_winner(bids):
                        agv.accept_mission(m)
                        m.status = MISSION_ASSIGNED
                        m.assigned_to = agv.agv_id
                        m.started_at = self.t
                        self.pallets[m.pallet_id].state = P_RESERVED
                        self.mission_manager.log.append(f"{agv.agv_id} gana la Misión {m.id}")
                        break

        # 3. Comportamiento y Movimiento de los AGVs

        # Posiciones ocupadas al inicio del paso
        reserved = {a.agv_id: a.pos.copy() for a in self.agvs}

        # Prioridad, primero quien va a cargar, luego menor bateria primero
        move_order = sorted(self.agvs, key=lambda a: (a.state != AGV_CHARGING, a.battery))

        for agv in move_order:
            # --- M4: conteo de pasos por estado (para utilizacion de la flota) ---
            if agv.state in (AGV_MOVING_TO_PALLET, AGV_TRANSPORTING):
                agv.active_steps += 1
            elif agv.state == AGV_CHARGING:
                agv.charging_steps += 1
            elif agv.state == AGV_IDLE:
                agv.idle_steps += 1

            # Viajar, esperar turno y cargar son fases distintas.
            if agv.state == AGV_CHARGING:
                if agv.charger is None:
                    agv.go_to_recharge(self.chargers)
                if agv.charger is not None:
                    self._move_with_collision_avoidance(agv, reserved)
                    at_charger = np.linalg.norm(agv.pos - np.array(agv.charger["pos"])) < 0.001
                    agv.charge_phase = "CHARGING" if at_charger else "TO_CHARGER"
                    if at_charger:
                        agv.battery = min(100.0, agv.battery + 4.0)
                        if agv.battery >= CHARGED_BATTERY_THRESHOLD:
                            agv.charger["occupied_by"] = None
                            agv.charger = None
                            agv.state = agv.suspended_state if agv.current_mission is not None else AGV_IDLE
                            agv.charge_phase = ""
                            target = self._current_target(agv)
                            agv.path = plan_path(agv, target) if target is not None else []
                if agv.current_mission is not None:
                    pallet = self.pallets[agv.current_mission.pallet_id]
                    if pallet.state == P_BEING_TRANSPORTED:
                        pallet.pos = agv.pos.copy()

            # Movimiento hacia el pallet
            elif agv.state == AGV_MOVING_TO_PALLET:
                pallet = self.pallets[agv.current_mission.pallet_id]
                self._move_with_collision_avoidance(agv, reserved)

                if len(agv.path) == 0:
                    agv.state = AGV_TRANSPORTING
                    pallet.state = P_BEING_TRANSPORTED
                    agv.path = plan_path(agv, agv.current_mission.destination)

                    if agv.current_mission.origin_station_id is not None:
                        self.stations_by_name[agv.current_mission.origin_station_id].release()
                    else:
                        self.production_line.release_by_pallet(pallet.id)

                    self.mission_manager.log.append(f"[EVENTO] {agv.agv_id} recogió {pallet.id}")

            # Transporte hacia la zona de entrega
            elif agv.state == AGV_TRANSPORTING:
                pallet = self.pallets[agv.current_mission.pallet_id]
                self._move_with_collision_avoidance(agv, reserved)
                pallet.pos = agv.pos.copy()

                if len(agv.path) == 0:
                    agv.state = AGV_IDLE
                    agv.current_mission.status = MISSION_COMPLETED
                    agv.current_mission.completed_at = self.t
                    pallet.state = P_DELIVERED
                    agv.completed_missions_count += 1
                    self.total_completed += 1

                    # La estacion de destino ahora tiene el pallet fisicamente
                    if agv.current_mission.dest_station_id is not None:
                        self.stations_by_name[agv.current_mission.dest_station_id].occupy(pallet.id)

                    self.mission_manager.log.append(f"[EVENTO] {agv.agv_id} entregó {pallet.id} ({agv.current_mission.id} completada)")
                    agv.current_mission = None

        for agv in self.agvs:
            if agv.state != AGV_CHARGING and agv.battery <= LOW_BATTERY_THRESHOLD:
                agv.go_to_recharge(self.chargers)
        self._record_frame()

"""# **Exportación a JSON (para Unity)**"""

def _to_serializable(obj):
    if isinstance(obj, np.ndarray):
        return [float(v) for v in obj]
    if isinstance(obj, dict):
        return {k: _to_serializable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_to_serializable(v) for v in obj]
    if isinstance(obj, (np.floating, np.integer)):
        return obj.item()
    if obj is None:
        return ""
    return obj

def export_simulation(model, path="simulation_export.json"):
    data = {
        "meta": {
            "width": WIDTH,
            "height": HEIGHT,
            "cell_size": CELL_SIZE,
            "frame_sample": FRAME_SAMPLE,
            "n_agvs": model.p.n_agvs,
            "total_steps": model.p.steps,
            "total_completed": model.total_completed,
            "total_missions": model.mission_counter - 1,
        },
        "zones": _to_serializable(zones_custom),
        "chargers": [{"name": c["name"], "pos": _to_serializable(c["pos"])} for c in chargers_custom],
        "stations": [{"name": s["name"], "kind": s["kind"], "pos": _to_serializable(s["pos"])}
                     for s in STATION_DEFINITIONS],
        "frames": _to_serializable(model.history),
        "log": model.mission_manager.log,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Exportado a {path} ({len(model.history)} frames)")

"""# **Función de Ejecución y cálculo de métricas**"""

def run_simulation(strategy, n_agvs=4, steps=800, seed=42, flow_scale=1.0, routing=ROUTING_BFS):
    """Corre una simulación completa con la estrategia dada, controlando la
    semilla para que baseline y propuesta reciban las mismas condiciones
    (mismo layout, mismos AGVs, mismas misiones generadas por los flujos).
    `flow_scale=1.0` reproduce los intervalos de referencia del reto sin
    modificarlos; valores distintos solo se usan en el escenario experimental
    adicional de la sección "Escenario de mayor contención", mas abajo.
    `routing` selecciona BFS (M4 original) o A* con penalizacion de congestion
    (M4-EXT, ver sección "Extensión: ruteo consciente de congestión")."""
    random.seed(seed)
    np.random.seed(seed)
    params = {'n_agvs': n_agvs, 'steps': steps, 'strategy': strategy, 'flow_scale': flow_scale, 'routing': routing}
    model = DistributionCenter(params)
    model.run(display=False)
    return model

def compute_metrics(model):
    total_steps = model.p.steps
    all_missions = list(model.mission_manager.missions.values())
    completed = [m for m in all_missions if m.status == MISSION_COMPLETED and m.started_at is not None]
    avg_mission_time = float(np.mean([m.completed_at - m.started_at for m in completed])) if completed else 0.0

    # Tiempo de espera = desde que la mision se publico (created_at) hasta que un AGV la acepto (started_at)
    started = [m for m in all_missions if m.started_at is not None and m.created_at is not None]
    avg_wait_time = float(np.mean([m.started_at - m.created_at for m in started])) if started else 0.0

    utilization = [(a.active_steps / total_steps) * 100 for a in model.agvs]
    charging_pct = [(a.charging_steps / total_steps) * 100 for a in model.agvs]
    maneuvers = sum(1 for line in model.mission_manager.log if line.startswith("[MANIOBRA]"))
    pending = sum(1 for m in all_missions if m.status != MISSION_COMPLETED)

    # Balance de carga: que tan parejo se reparten las misiones completadas
    # entre los AGVs (desviacion estandar de misiones completadas por AGV).
    # Es la metrica mas directa para medir el efecto del termino L_i de la
    # heuristica (fairness), sin depender de efectos secundarios de ruteo.
    workload_balance = float(np.std([a.completed_missions_count for a in model.agvs]))

    return {
        "Misiones generadas": model.mission_counter - 1,
        "Misiones completadas": model.total_completed,
        "Throughput (misiones/paso)": model.total_completed / total_steps,
        "Tiempo promedio de misión (pasos)": avg_mission_time,
        "Tiempo promedio de espera (pasos)": avg_wait_time,
        "Utilización de AGVs (%)": float(np.mean(utilization)),
        "Disponibilidad de la flota (%)": 100.0 - float(np.mean(charging_pct)),
        "Distancia promedio recorrida": float(np.mean([a.distance_traveled for a in model.agvs])),
        "Eventos de carga": sum(a.charging_events for a in model.agvs),
        "Tiempo promedio de carga (pasos)": float(np.mean([a.charging_steps for a in model.agvs])),
        "Balance de carga (std misiones/AGV)": workload_balance,
        "Conflictos de ruta (maniobras)": maneuvers,
        "Misiones pendientes": pending,
    }

def print_agv_utilization(model, label):
    total_steps = model.p.steps
    print(f"\nUtilización por AGV ({label}):")
    for a in model.agvs:
        print(f"  {a.agv_id}: {(a.active_steps / total_steps) * 100:5.1f}% activo | "
              f"{(a.charging_steps / total_steps) * 100:5.1f}% cargando | "
              f"{a.completed_missions_count} misiones | {a.distance_traveled:.1f} unidades recorridas")

"""# **M4: Problema identificado y estrategia propuesta**

**Problema:** en M3, `evaluate_mission` (ahora `_utility_baseline`) asigna cada
misión al AGV mas cercano al pallet, sin mirar nada mas. Con esto: (1) un AGV
que ya completo muchas misiones sigue ganando subastas solo por estar cerca,
mientras otro AGV se queda ocioso (desbalance de carga de trabajo), y (2) el
AGV ganador puede terminar entrando a una zona donde ya hay otro AGV activo,
generando el tipo de maniobras/bloqueos que registra `_resolve_deadlock`
(congestión evitable).

**Técnica seleccionada:** dos mejoras combinadas. (1) heurística de utilidad
para la negociación tipo Contract-Net (`MissionManager.publish_mission` +
`collect_bids`), con una función de puja mas rica, que decide "¿qué AGV debe
tomar la misión?". (2) ruteo consciente de congestión: `find_path_grid`
(BFS, M3) solo evita racks; la propuesta usa `find_path_astar_congestion`
(A*) via `plan_path`, que ademas penaliza pasar cerca de otro AGV que ya
esta en movimiento, para decidir "¿por dónde llega?" evitando de entrada
corredores ocupados en vez de descubrir el choque a medio camino. El
Mission Manager solo publica la misión y reune las pujas; la comparación de
quién ganó ocurre dentro de cada `AGVAgent` (`determine_if_winner`), no en
el Mission Manager.

**Fórmula propuesta:**

U_{i,m} = -w_d * D_{i,m} + w_b * B_i - w_l * L_i - w_c * C_i

- D_{i,m}: distancia Manhattan del AGV i al origen de la misión m.
- B_i: batería actual del AGV i (0-100).
- L_i: carga de trabajo acumulada (misiones ya completadas por el AGV i).
- C_i: congestión estimada (# de otros AGVs activos cerca del origen de m).
- Pesos usados: w_d=1.0, w_b=0.3, w_l=15.0, w_c=25.0 (constantes
  `W_DISTANCE`, `W_BATTERY`, `W_WORKLOAD`, `W_CONGESTION`).

El AGV preferido es `argmax_i U_{i,m}`. El Mission Manager (`collect_bids`)
solo reune las pujas en un tablón visible para todos; cada AGV, con ese mismo
tablón, calcula por su cuenta si su puja fue la máxima (`determine_if_winner`)
y de ser así se autoasigna la misión (`accept_mission`). El Mission Manager
nunca compara AGVs ni decide un ganador (evita funciones tipo
`select_best_AGV()` o `assign_mission()` centralizadas).

**Eventos dinámicos (sección 11 del reto):** se agregaron los dos eventos
pedidos: peatones que aparecen temporalmente sobre el mapa y bloquean el
paso de los AGVs (`spawn_pedestrian`/`update_pedestrians`), y estaciones que
entran en alarma/fuera de servicio por un tiempo limitado
(`update_station_alarms`, usando el `set_out_of_service`/`restore_service`
de `StationAgent`). Ambos eventos usan la misma semilla en baseline y
propuesta, para que la comparación siga siendo justa.

**Baseline vs propuesta:** el baseline usa la subasta original
(`_utility_baseline`) y BFS (`ROUTING_BFS`) sin cambios de M3. La propuesta
usa la subasta con heurística (`_utility_proposed`) Y el ruteo A* consciente
de congestión (`ROUTING_ASTAR`) juntos — no se comparan por separado porque
la subasta, aislada, casi no tiene impacto bajo los intervalos oficiales del
reto (verificado: con esos intervalos casi nunca hay dos AGVs libres
compitiendo por la misma misión), mientras que el ruteo sí actúa en cada
misión. Combinar ambas es la solución completa que se está proponiendo, y la
diferencia ya se ve directamente bajo los intervalos oficiales del reto
(`comparison_df`, más abajo) — no hace falta un escenario adicional para
demostrarla.

# **Ejecución: Baseline vs Propuesta**
"""
