# -*- coding: utf-8 -*-
"""M4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15S2t1-RQJz0Mmne1tZQJzRgbY3JWfRuI
"""


"""# **Librerias**"""

import agentpy as ap
import numpy as np
import json
import random
from collections import deque

"""# **Constantes**"""

# Tamaño Entorno
WIDTH, HEIGHT = 450, 300

# Estados AGVs
AGV_IDLE = 'IDLE'
AGV_MOVING_TO_PALLET = 'MOVING_TO_PALLET'
AGV_TRANSPORTING = 'TRANSPORTING'
AGV_CHARGING = 'CHARGING'

# Estados Pallets
P_STORED = 'ALMACENADO'
P_RESERVED = 'RESERVADO'
P_BEING_TRANSPORTED = 'SIENDO_TRANSPORTADO'
P_DELIVERED = 'ENTREGADO'

# Estados Misiones
MISSION_PENDING = 'PENDIENTE'
MISSION_ASSIGNED = 'ASIGNADA'
MISSION_COMPLETED = 'COMPLETADA'

# Limites de Bateria
LOW_BATTERY_THRESHOLD = 30.0
CHARGED_BATTERY_THRESHOLD = 80.0

# Distancia minima entre AGVs
AGV_SAFETY_RADIUS = 32

# Que tan seguido se graba una frame para animar
FRAME_SAMPLE = 1

# Pasos cuando dos AGVs estan bloqueados antes de forzar un desvio
DEADLOCK_THRESHOLD = 4

# Cuanto se queda en verde la mision completada en el panel antes de desaparecer
MISSION_COMPLETED_DISPLAY_STEPS = 10

# Estados Estaciones
STATION_AVAILABLE = "AVAILABLE"
STATION_RESERVED = "RESERVED"
STATION_OCCUPIED = "OCCUPIED"
STATION_OUT_OF_SERVICE = "OUT_OF_SERVICE"

# Flujos logisticos
FLOW_1_INTERVAL = 60   # Linea de produccion -> Rack o Caja de salida
FLOW_2_INTERVAL = 90   # Rack -> Caja de camion de salida
FLOW_3_INTERVAL = 120   # Caja de camion de entrada -> Rack
DOCK_DEPARTURE_INTERVAL = 30  # cada cuanto un camion recoge un pallet listo en un dock y lo libera

# Probabilidades de destino de flujo 1
P_DEST_RACK = 0.60
P_DEST_DOCK = 0.40

# --- M4: Estrategias de negociacion de misiones ---
# BASELINE: el AGV mas cercano al pallet gana (con ligero desempate por bateria).
# PROPOSED: heuristica de utilidad que ademas balancea carga de trabajo y evita
# mandar AGVs hacia zonas ya congestionadas por otros AGVs.
STRATEGY_BASELINE = "baseline"
STRATEGY_PROPOSED = "proposed"

# Pesos de U_{i,m} = -w_d*D_{i,m} + w_b*B_i - w_l*L_i - w_c*C_i
W_DISTANCE = 1.0     # penaliza distancia al pallet (misma escala que el baseline)
W_BATTERY = 0.3      # premia bateria alta (preferir AGVs mas cargados)
W_WORKLOAD = 15.0    # penaliza AGVs que ya han completado mas misiones (fairness)
W_CONGESTION = 25.0  # penaliza AGVs cercanos a otros AGVs activos junto al origen
CONGESTION_RADIUS = 40.0  # radio (unidades de mundo) para contar AGVs cercanos

# --- M4: Eventos dinamicos (requeridos por el reto, seccion 11) ---
# Peatones: obstaculos moviles temporales sobre las rutas de los AGVs
PEDESTRIAN_INTERVAL = 70   # cada cuanto puede aparecer un peaton nuevo
PEDESTRIAN_DURATION = 25   # pasos que el peaton permanece bloqueando esa zona
PEDESTRIAN_RADIUS = 12     # radio de bloqueo alrededor del peaton

# Estaciones en alarma / fuera de servicio temporalmente
STATION_ALARM_INTERVAL = 150  # cada cuanto se intenta poner una estacion en alarma
STATION_ALARM_DURATION = 40   # pasos que la estacion permanece fuera de servicio

"""# **Entorno**"""

def make_zone(name, x, y, width, height, color):
    return {"name": name, "x": x, "y": y, "width": width, "height": height, "color": color}

zones_custom = [
    # Production Lines
    make_zone("Prod Line 1", 0, 225, 45, 15, "cornflowerblue"),
    make_zone("Prod Line 2", 0, 200, 45, 15, "cornflowerblue"),
    make_zone("Prod Line 3", 0, 175, 45, 15, "cornflowerblue"),
    make_zone("Prod Line 4", 0, 150, 45, 15, "cornflowerblue"),
    # Racks
    make_zone("Rack A", 150, 200, 100, 22, "sandybrown"),
    make_zone("Rack B", 150, 100, 100, 22, "sandybrown"),
    make_zone("Rack C", 200, 278, 100, 22, "sandybrown"),
    make_zone("Rack D", 300, 111, 22, 100, "sandybrown"),
    make_zone("Rack E", 200, 0, 100, 22, "sandybrown"),
    # Truck Docks
    make_zone("Dock 1", 425, 225, 20, 30, "yellowgreen"),
    make_zone("Dock 2", 425, 185, 20, 30, "yellowgreen"),
    make_zone("Dock 3", 425, 145, 20, 30, "yellowgreen"),
    make_zone("Dock 4", 425, 105, 20, 30, "yellowgreen")
]

# Estaciones de Carga
chargers_custom = [
    {"name": "Charger 1", "pos": (100, 275), "occupied_by": None},
    {"name": "Charger 2", "pos": (375, 275), "occupied_by": None}
]

CELL_SIZE = 5
# Tamaño del vehículo y de la caja. Unity lee estas dimensiones del JSON.
AGV_DIAMETER = 26.0
PALLET_DIAMETER = 10.0
AGV_BODY_RADIUS = AGV_DIAMETER / 2
AGV_CLEARANCE = AGV_BODY_RADIUS + 4.0
PEDESTRIAN_RADIUS = max(PEDESTRIAN_RADIUS, AGV_BODY_RADIUS + 4.0)
SERVICE_MARGIN = AGV_CLEARANCE + CELL_SIZE
GRID_W = WIDTH // CELL_SIZE
GRID_H = HEIGHT // CELL_SIZE

def world_to_grid(pos):
    gx = int(np.clip(pos[0] // CELL_SIZE, 0, GRID_W - 1))
    gy = int(np.clip(pos[1] // CELL_SIZE, 0, GRID_H - 1))
    return (gx, gy)

def grid_to_world(grid_pos):
    return np.array([grid_pos[0] * CELL_SIZE + CELL_SIZE / 2,
                     grid_pos[1] * CELL_SIZE + CELL_SIZE / 2], dtype=float)

def build_occupancy_grid(zones):
    # Centros transitables: el cuerpo completo debe caber fuera de zonas y paredes.
    xs = (np.arange(GRID_W) + 0.5) * CELL_SIZE
    ys = (np.arange(GRID_H) + 0.5) * CELL_SIZE
    xx, yy = np.meshgrid(xs, ys)
    blocked = ((xx < AGV_CLEARANCE) | (xx > WIDTH - AGV_CLEARANCE)
               | (yy < AGV_CLEARANCE) | (yy > HEIGHT - AGV_CLEARANCE))
    for z in zones:
        blocked |= ((xx > z["x"] - AGV_CLEARANCE)
                    & (xx < z["x"] + z["width"] + AGV_CLEARANCE)
                    & (yy > z["y"] - AGV_CLEARANCE)
                    & (yy < z["y"] + z["height"] + AGV_CLEARANCE))
    return blocked.astype(int)

NAV_GRID = build_occupancy_grid(zones_custom)

def segment_clear_of_obstacles(start, end, clearance=AGV_CLEARANCE):
    """Comprueba el segmento completo, no solo su celda de destino."""
    for pos in (start, end):
        if not (clearance <= pos[0] <= WIDTH - clearance
                and clearance <= pos[1] <= HEIGHT - clearance):
            return False
    for zone in zones_custom:
        enter, leave = 0.0, 1.0
        for axis, key, size in ((0, "x", "width"), (1, "y", "height")):
            low = zone[key] - clearance
            high = zone[key] + zone[size] + clearance
            delta = end[axis] - start[axis]
            if abs(delta) < 1e-9:
                if start[axis] <= low or start[axis] >= high:
                    break
            else:
                a, b = sorted(((low - start[axis]) / delta, (high - start[axis]) / delta))
                enter, leave = max(enter, a), min(leave, b)
                if enter >= leave:
                    break
        else:
            if enter < leave:
                return False
    return True

def zone_by_name(name):
    return next(z for z in zones_custom if z["name"] == name)

def edge_point(zone, side, margin=SERVICE_MARGIN):
    x, y, w, h = zone["x"], zone["y"], zone["width"], zone["height"]
    if side == "west":
        return (x - margin, y + h / 2)
    if side == "east":
        return (x + w + margin, y + h / 2)
    if side == "south":
        return (x + w / 2, y - margin)
    if side == "north":
        return (x + w / 2, y + h + margin)
    raise ValueError(side)

# Lado de cada rack que da hacia el pasillo abierto (para que los pallets
# aparezcan pegados a una orilla, no flotando en medio del pasillo)
RACK_SIDES = {
    "Rack A": "south",
    "Rack B": "north",
    "Rack C": "south",
    "Rack D": "west",
    "Rack E": "north",
}

DOCK_NAMES = ["Dock 1", "Dock 2", "Dock 3", "Dock 4"]

# Definicion de cada estacion con su punto accesible
STATION_DEFINITIONS = (
    [{"name": n, "kind": "RACK", "pos": edge_point(zone_by_name(n), s)} for n, s in RACK_SIDES.items()] +
    [{"name": n, "kind": "DOCK", "pos": edge_point(zone_by_name(n), "west")} for n in DOCK_NAMES]
)


class StationAgent(ap.Agent):

    def setup(self):
        self.station_id = None
        self.kind = None
        self.pos = np.array([0.0, 0.0])
        self.state = STATION_AVAILABLE
        self.current_pallet_id = None

    def is_available(self):
        return self.state == STATION_AVAILABLE

    def reserve(self, pallet_id):
        # La estacion es el destino de una mision en camino
        self.state = STATION_RESERVED
        self.current_pallet_id = pallet_id

    def occupy(self, pallet_id):
        # El pallet ya esta fisicamente en la estacion (llego o fue generado ahi)
        self.state = STATION_OCCUPIED
        self.current_pallet_id = pallet_id

    def release(self):
        # El pallet salio de la estacion y vuelve a estar libre.
        self.state = STATION_AVAILABLE
        self.current_pallet_id = None

    def set_out_of_service(self):
        self.state = STATION_OUT_OF_SERVICE

    def restore_service(self):
        self.state = STATION_AVAILABLE


class ProductionLine:

    def __init__(self, outlet_positions):
        self.outlets = [{"pos": np.array(p, dtype=float), "pallet_id": None} for p in outlet_positions]

    def free_outlets(self):
        return [o for o in self.outlets if o["pallet_id"] is None]

    def occupy_outlet(self, outlet, pallet_id):
        outlet["pallet_id"] = pallet_id

    def release_by_pallet(self, pallet_id):
        for o in self.outlets:
            if o["pallet_id"] == pallet_id:
                o["pallet_id"] = None

def find_path_grid(start_pos, goal_pos, grid):
    start = world_to_grid(start_pos)
    goal = world_to_grid(goal_pos)

    if start == goal:
        return [np.array(goal_pos, dtype=float)]

    queue = deque([start])
    came_from = {start: None}
    directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
    found = False

    while queue:
        current = queue.popleft()
        if current == goal:
            found = True
            break

        for dx, dy in directions:
            neighbor = (current[0] + dx, current[1] + dy)
            nx, ny = neighbor

            if 0 <= nx < GRID_W and 0 <= ny < GRID_H:
                if (grid[ny, nx] == 0 or neighbor == goal) and neighbor not in came_from:
                    came_from[neighbor] = current
                    queue.append(neighbor)

    if not found:
        return [np.array(goal_pos, dtype=float)]

    path = []
    curr = goal
    while curr is not None:
        path.append(grid_to_world(curr))
        curr = came_from[curr]
    path.reverse()
    path[-1] = np.array(goal_pos, dtype=float)
    return path

"""# **Pallet, Mission y MissionManager**"""

class Pallet:
    def __init__(self, p_id, pos, storage_zone):
        self.id = p_id
        self.storage_zone = storage_zone
        self.storage_level = int(p_id[1:]) % 2
        self.removed = False
        self.pos = np.array(pos, dtype=float)
        self.state = P_STORED

class Mission:
    def __init__(self, m_id, p_id, origin, destination, origin_station_id=None, dest_station_id=None, created_at=None):
        self.id = m_id
        self.pallet_id = p_id
        self.origin = np.array(origin, dtype=float)
        self.destination = np.array(destination, dtype=float)
        self.status = MISSION_PENDING
        self.assigned_to = None
        self.origin_station_id = origin_station_id
        self.dest_station_id = dest_station_id
        self.created_at = created_at
        self.started_at = None
        self.completed_at = None

class MissionManager:
    """Tablon de anuncios de misiones: SOLO publica misiones y reune las pujas
    que cada AGV calcula por su cuenta. No compara AGVs ni decide quien gana
    (esa decision la toma cada AGVAgent con `determine_if_winner`, ver mas abajo),
    para no convertirse en un controlador centralizado."""

    def __init__(self, missions):
        self.missions = {m.id: m for m in missions}
        self.log = []
        self._published = set()

    def publish_mission(self, mission):
        if mission.id not in self._published:
            self.log.append(f"\n[SUBASTA] Misión {mission.id} publicada (Pallet: {mission.pallet_id})")
            self._published.add(mission.id)

    def collect_bids(self, mission, agv_list):
        bids = {}
        for agv in agv_list:
            bid = agv.evaluate_mission(mission)
            if bid is not None:
                self.log.append(f"  > {agv.agv_id} puja: {bid:.2f}")
                bids[agv.agv_id] = bid
            else:
                self.log.append(f"  > {agv.agv_id} no disponible (Estado: {agv.state}, Bat: {agv.battery:.1f}%)")
        return bids

"""# **Modelo Agente**"""

class AGVAgent(ap.Agent):
    def setup(self):
        self.agv_id = f"AGV-{self.id}"
        self.pos = np.array([0.0, 0.0], dtype=float)
        self.state = AGV_IDLE
        self.battery = 100.0
        self.speed = 5.0
        self.current_mission = None
        self.distance_traveled = 0.0
        self.completed_missions_count = 0
        self.stuck_steps = 0
        self.path = []
        self.charger = None

        # --- M4: metricas por AGV ---
        self.active_steps = 0     # pasos moviendose hacia un pallet o transportando
        self.charging_steps = 0   # pasos en estacion de carga
        self.idle_steps = 0       # pasos sin mision ni carga
        self.charging_events = 0  # veces que fue a recargar

    def evaluate_mission(self, mission):
        # Si está ocupado o con batería baja, no participa en subastas
        if self.state != AGV_IDLE or self.battery <= LOW_BATTERY_THRESHOLD:
            return None
        strategy = getattr(self.model.p, "strategy", STRATEGY_BASELINE)
        if strategy == STRATEGY_PROPOSED:
            return self._utility_proposed(mission)
        return self._utility_baseline(mission)

    def _distance_to(self, point):
        return np.abs(self.pos[0] - point[0]) + np.abs(self.pos[1] - point[1])

    def _utility_baseline(self, mission):
        # BASELINE: AGV mas cercano al pallet gana, con ligero desempate por bateria
        dist_to_pallet = self._distance_to(mission.origin)
        return - dist_to_pallet + (self.battery * 0.1)

    def _route_congestion(self, mission):
        # Cuenta AGVs activos (no IDLE) cerca del punto medio entre ESTE AGV y
        # el origen de la mision, como proxy de que SU camino hacia alla ya
        # esta ocupado. Debe depender de self.pos: si dependiera solo de la
        # posicion de la mision, todos los AGVs que pujan por la misma mision
        # verian el mismo valor y el termino nunca podria cambiar quien gana.
        midpoint = (self.pos + mission.origin) / 2.0
        return sum(
            1 for other in self.model.agvs
            if other.agv_id != self.agv_id and other.state != AGV_IDLE
            and np.linalg.norm(other.pos - midpoint) < CONGESTION_RADIUS
        )

    def _utility_proposed(self, mission):
        # PROPUESTA: U_{i,m} = -w_d*D_{i,m} + w_b*B_i - w_l*L_i - w_c*C_i
        dist_to_pallet = self._distance_to(mission.origin)
        workload = self.completed_missions_count
        congestion = self._route_congestion(mission)
        return (- W_DISTANCE * dist_to_pallet
                + W_BATTERY * self.battery
                - W_WORKLOAD * workload
                - W_CONGESTION * congestion)

    def determine_if_winner(self, bids):
        """Con el tablon de pujas ya publicado por el Mission Manager (todas
        las pujas son visibles para todos), cada AGV decide POR SI MISMO si
        fue quien ofrecio la mejor puja. En caso de empate, gana el agv_id
        menor (regla determinista que cualquier AGV puede evaluar de forma
        independiente, sin que el Mission Manager compare a nadie)."""
        if self.agv_id not in bids:
            return False
        best_bid = max(bids.values())
        tied = sorted(agv_id for agv_id, b in bids.items() if b == best_bid)
        return self.agv_id == tied[0]

    def accept_mission(self, mission):
        # El AGV acepta la mision para si mismo (auto-asignacion)
        self.current_mission = mission
        self.state = AGV_MOVING_TO_PALLET
        self.path = find_path_grid(self.pos, mission.origin, NAV_GRID)

    def go_to_recharge(self, chargers):
      free = [c for c in chargers if c["occupied_by"] is None]
      if not free:
          return False  # ningún cargador libre: el AGV se queda esperando
      closest = min(free, key=lambda c: np.linalg.norm(self.pos - np.array(c["pos"])))
      closest["occupied_by"] = self.agv_id
      self.charger = closest
      self.state = AGV_CHARGING
      self.charging_events += 1
      self.path = find_path_grid(self.pos, np.array(closest["pos"], dtype=float), NAV_GRID)
      return True

    def peek_next_position(self):
        if not self.path:
            return self.pos.copy()
        target = self.path[0]
        dir_vec = target - self.pos
        dist = np.linalg.norm(dir_vec)
        if dist <= self.speed or dist < 1e-3:
            return target.copy()
        return self.pos + (dir_vec / dist) * self.speed

    def follow_path(self):
        if not self.path:
            return

        target = self.path[0]
        dir_vec = target - self.pos
        dist = np.linalg.norm(dir_vec)

        if dist <= self.speed or dist < 1e-3:
            self.pos = target.copy()
            self.path.pop(0)
            step_dist = dist
        else:
            step_vector = (dir_vec / dist) * self.speed
            self.pos += step_vector
            step_dist = self.speed

        self.distance_traveled += step_dist
        self.battery = max(0.0, self.battery - (step_dist * 0.035))

"""# **Modelo Multiagente**"""

class DistributionCenter(ap.Model):
    def setup(self):
        self.agvs = ap.AgentList(self, self.p.n_agvs, AGVAgent)
        pos_ini = [(80, 50), (80, 120), (80, 180), (80, 240)]
        for i, agv in enumerate(self.agvs):
            agv.pos = np.array(pos_ini[i % len(pos_ini)], dtype=float)

        self.production_line = ProductionLine([
            edge_point(z, "east") for z in zones_custom if z["name"].startswith("Prod Line")
        ])

        self.chargers = [dict(c, occupied_by=None) for c in chargers_custom]

        self.stations = ap.AgentList(self, len(STATION_DEFINITIONS), StationAgent)
        for station, definition in zip(self.stations, STATION_DEFINITIONS):
            station.station_id = definition["name"]
            station.kind = definition["kind"]
            station.pos = np.array(definition["pos"], dtype=float)
        self.stations_by_name = {s.station_id: s for s in self.stations}

        self.mission_manager = MissionManager([])
        self.pallets = {}
        self.mission_counter = 1
        self.pallet_counter = 1
        self.total_completed = 0
        self.reassignments = 0
        self.history = []

        # Ultimo paso en que cada flujo genero mision
        self.last_flow1_t = -FLOW_1_INTERVAL
        self.last_flow2_t = -FLOW_2_INTERVAL
        self.last_flow3_t = -FLOW_3_INTERVAL
        self.last_departure_t = -DOCK_DEPARTURE_INTERVAL

        # --- M4: eventos dinamicos ---
        self.pedestrians = []  # [{"pos": np.array, "until": t}]
        self.last_pedestrian_t = -PEDESTRIAN_INTERVAL
        self.station_alarms = {}  # {station_id: t_restauracion}
        self.last_alarm_t = -STATION_ALARM_INTERVAL

        self._record_frame()

    def spawn_pedestrian(self):
        gx, gy = np.random.randint(0, GRID_W), np.random.randint(0, GRID_H)
        tries = 0
        while NAV_GRID[gy, gx] == 1 and tries < 10:
            gx, gy = np.random.randint(0, GRID_W), np.random.randint(0, GRID_H)
            tries += 1
        if NAV_GRID[gy, gx] == 1:
            return
        pos = grid_to_world((gx, gy))
        if any(np.linalg.norm(pos - agv.pos) < PEDESTRIAN_RADIUS + CELL_SIZE for agv in self.agvs):
            return
        self.pedestrians.append({"pos": pos, "until": self.t + PEDESTRIAN_DURATION})
        self.mission_manager.log.append(f"[EVENTO] Peatón cruza cerca de ({pos[0]:.0f}, {pos[1]:.0f})")

    def update_pedestrians(self):
        if self.t - self.last_pedestrian_t >= PEDESTRIAN_INTERVAL:
            self.spawn_pedestrian()
            self.last_pedestrian_t = self.t
        self.pedestrians = [p for p in self.pedestrians if p["until"] > self.t]

    def update_station_alarms(self):
        for station_id, restore_t in list(self.station_alarms.items()):
            if self.t >= restore_t:
                self.stations_by_name[station_id].restore_service()
                self.mission_manager.log.append(f"[EVENTO] {station_id} vuelve a estar disponible")
                del self.station_alarms[station_id]

        if self.t - self.last_alarm_t >= STATION_ALARM_INTERVAL:
            candidates = [s for s in self.stations if s.is_available()]
            if candidates:
                station = candidates[np.random.randint(len(candidates))]
                station.set_out_of_service()
                self.station_alarms[station.station_id] = self.t + STATION_ALARM_DURATION
                self.mission_manager.log.append(f"[EVENTO] {station.station_id} entra en alarma / fuera de servicio")
            self.last_alarm_t = self.t


    def try_flow_1(self):
        # Flujo 1: Linea de produccion -> Rack o Caja de salida (60%/40%)
        free = self.production_line.free_outlets()
        if not free:
            return False  # sin salidas libres: no se genera, no se acumula

        outlet = free[np.random.randint(len(free))]

        dest_kind = "RACK" if np.random.random() < P_DEST_RACK else "DOCK"
        candidates = [s for s in self.stations if s.kind == dest_kind and s.is_available()]
        if not candidates:
            return False  # sin destino disponible: no se genera
        dest_station = candidates[np.random.randint(len(candidates))]

        pallet_id = f"P{self.pallet_counter}"
        self.pallet_counter += 1
        production_zone = next(z["name"] for z in zones_custom
                               if z["name"].startswith("Prod Line")
                               and np.allclose(edge_point(z, "east"), outlet["pos"]))
        self.pallets[pallet_id] = Pallet(pallet_id, outlet["pos"], production_zone)
        self.production_line.occupy_outlet(outlet, pallet_id)
        dest_station.reserve(pallet_id)

        m_id = f"M{self.mission_counter}"
        self.mission_counter += 1
        mission = Mission(m_id, pallet_id, outlet["pos"], dest_station.pos,
                           origin_station_id=None, dest_station_id=dest_station.station_id,
                           created_at=self.t)
        self.mission_manager.missions[m_id] = mission
        self.mission_manager.log.append(
            f"[FLUJO 1] {m_id}: Producción -> {dest_station.station_id} ({dest_kind}), pallet {pallet_id}"
        )
        return True

    def try_flow_2(self):
        # Flujo 2: Rack -> Caja de camión de salida
        origin_candidates = [s for s in self.stations if s.kind == "RACK" and s.state == STATION_OCCUPIED
                             and not any(m.pallet_id == s.current_pallet_id and m.status != MISSION_COMPLETED
                                         for m in self.mission_manager.missions.values())]
        if not origin_candidates:
            return False
        origin_station = origin_candidates[np.random.randint(len(origin_candidates))]

        dest_candidates = [s for s in self.stations if s.kind == "DOCK" and s.is_available()]
        if not dest_candidates:
            return False
        dest_station = dest_candidates[np.random.randint(len(dest_candidates))]

        pallet_id = origin_station.current_pallet_id
        dest_station.reserve(pallet_id)

        m_id = f"M{self.mission_counter}"
        self.mission_counter += 1
        mission = Mission(m_id, pallet_id, origin_station.pos, dest_station.pos,
                           origin_station_id=origin_station.station_id, dest_station_id=dest_station.station_id,
                           created_at=self.t)
        self.mission_manager.missions[m_id] = mission
        self.mission_manager.log.append(
            f"[FLUJO 2] {m_id}: {origin_station.station_id} -> {dest_station.station_id}, pallet {pallet_id}"
        )
        return True

    def try_flow_3(self):
        # Flujo 3: Caja de camión de entrada -> Rack
        origin_candidates = [s for s in self.stations if s.kind == "DOCK" and s.is_available()]
        if not origin_candidates:
            return False
        origin_station = origin_candidates[np.random.randint(len(origin_candidates))]

        dest_candidates = [s for s in self.stations if s.kind == "RACK" and s.is_available()]
        if not dest_candidates:
            return False
        dest_station = dest_candidates[np.random.randint(len(dest_candidates))]

        pallet_id = f"P{self.pallet_counter}"
        self.pallet_counter += 1
        self.pallets[pallet_id] = Pallet(pallet_id, origin_station.pos, origin_station.station_id)
        origin_station.occupy(pallet_id)
        dest_station.reserve(pallet_id)

        m_id = f"M{self.mission_counter}"
        self.mission_counter += 1
        mission = Mission(m_id, pallet_id, origin_station.pos, dest_station.pos,
                           origin_station_id=origin_station.station_id, dest_station_id=dest_station.station_id,
                           created_at=self.t)
        self.mission_manager.missions[m_id] = mission
        self.mission_manager.log.append(
            f"[FLUJO 3] {m_id}: {origin_station.station_id} -> {dest_station.station_id}, pallet {pallet_id}"
        )
        return True

    def try_dock_departure(self):
        # Intentar vaciar uno de los docks
        occupied_docks = [s for s in self.stations if s.kind == "DOCK" and s.state == STATION_OCCUPIED
                          and self.pallets[s.current_pallet_id].state == P_DELIVERED
                          and not any(m.pallet_id == s.current_pallet_id and m.status != MISSION_COMPLETED
                                      for m in self.mission_manager.missions.values())]
        if not occupied_docks:
            return False
        dock = occupied_docks[np.random.randint(len(occupied_docks))]
        self.mission_manager.log.append(
            f"[DESPACHO] Camión recoge {dock.current_pallet_id} en {dock.station_id}, dock queda libre"
        )
        self.pallets[dock.current_pallet_id].removed = True
        self.pallets[dock.current_pallet_id].storage_zone = None
        dock.release()
        return True

    def run_flow_generator(self):
        # Correr la revision y generacion de cada flujo. `flow_scale` es un
        # parametro opcional (default 1.0 = intervalos de referencia del reto
        # sin modificar) que permite correr un escenario experimental adicional
        # con mas o menos misiones por unidad de tiempo, sin tocar el escenario
        # de referencia por default.
        scale = getattr(self.p, "flow_scale", 1.0)
        f1, f2, f3 = FLOW_1_INTERVAL / scale, FLOW_2_INTERVAL / scale, FLOW_3_INTERVAL / scale
        if self.t - self.last_flow1_t >= f1:
            if self.try_flow_1():
                self.last_flow1_t = self.t
        if self.t - self.last_flow2_t >= f2:
            if self.try_flow_2():
                self.last_flow2_t = self.t
        if self.t - self.last_flow3_t >= f3:
            if self.try_flow_3():
                self.last_flow3_t = self.t
        if self.t - self.last_departure_t >= DOCK_DEPARTURE_INTERVAL:
            if self.try_dock_departure():
                self.last_departure_t = self.t

    def _record_frame(self):
        if self.t % FRAME_SAMPLE != 0:
            return
        self.history.append({
            "t": self.t,
            "agvs": [{"id": a.agv_id, "pos": a.pos.copy(), "battery": a.battery, "state": a.state} for a in self.agvs],
            "pallets": [{"id": p.id, "pos": p.pos.copy(), "state": p.state, "storage_zone": p.storage_zone, "storage_level": p.storage_level, "removed": p.removed} for p in self.pallets.values()],
            "stations": [{"id": s.station_id, "state": s.state, "pallet": s.current_pallet_id} for s in self.stations],
            "missions": [{"id": m.id, "pallet": m.pallet_id, "status": m.status, "assigned": m.assigned_to}
                        for m in self.mission_manager.missions.values()
                        if m.status != MISSION_COMPLETED
                        or (m.completed_at is not None and self.t - m.completed_at < MISSION_COMPLETED_DISPLAY_STEPS)],
            "pedestrians": [{"pos": p["pos"].copy()} for p in self.pedestrians],
            "completed": self.total_completed
        })

    def _resolve_deadlock(self, agv, reserved):
        # Resolver atoron entre dos AGVs. Devuelve True si encontro un desvio
        # valido, False si no (para que quien llama sepa si debe seguir
        # escalando en vez de reiniciar el conteo y repetir el mismo intento
        # fallido para siempre).
        if not agv.path:
            return False

        # Si hay otro AGV muy cerca, normalmente solo maniobra el de mayor id
        # y el de menor id espera, para que no maniobren los dos a la vez y
        # queden moviendose de un lado a otro. Pero si ya llevamos varios
        # ciclos sin resolver nada (el de mayor id tambien esta atorado, p.ej.
        # contra un rack), esa prioridad estricta produce un livelock: nadie
        # se mueve nunca. Tras esperar suficiente, se permite que el de menor
        # id tambien intente su propio desvio.
        own_num = int(agv.agv_id.split("-")[1])
        nearby_higher = any(
            oid != agv.agv_id
            and np.linalg.norm(agv.pos - opos) < AGV_SAFETY_RADIUS * 2
            and int(oid.split("-")[1]) > own_num
            for oid, opos in reserved.items()
        )
        escalating = agv.stuck_steps >= DEADLOCK_THRESHOLD * 3
        if nearby_higher and not escalating:
            return False

        target = agv.path[0]
        direction = target - agv.pos
        dist = np.linalg.norm(direction)
        if dist < 1e-6:
            return False

        unit = direction / dist
        perp = np.array([-unit[1], unit[0]])

        # Mientras mas tiempo lleve atorado, se prueban mas angulos y mas
        # distancias de desvio, en vez de repetir para siempre los dos mismos
        # puntos perpendiculares (que pueden estar bloqueados permanentemente
        # por un rack de un lado y otro AGV del otro).
        angle_steps = min(1 + agv.stuck_steps // DEADLOCK_THRESHOLD, 4)
        candidate_dirs = [perp, -perp]
        for k in range(1, angle_steps):
            theta = k * (np.pi / (2 * (angle_steps + 1)))
            cos_t, sin_t = np.cos(theta), np.sin(theta)
            rot = np.array([[cos_t, -sin_t], [sin_t, cos_t]])
            candidate_dirs.append(rot @ perp)
            candidate_dirs.append(rot @ -perp)
            candidate_dirs.append(rot.T @ perp)
            candidate_dirs.append(rot.T @ -perp)

        base_detour = AGV_SAFETY_RADIUS + CELL_SIZE * 2
        distance_scales = [1.0, 1.5, 2.0] if agv.stuck_steps >= DEADLOCK_THRESHOLD * 2 else [1.0]

        for scale in distance_scales:
            detour_dist = base_detour * scale
            for side in candidate_dirs:
                candidate = agv.pos + side * detour_dist
                candidate = np.clip(candidate, [CELL_SIZE, CELL_SIZE], [WIDTH - CELL_SIZE, HEIGHT - CELL_SIZE])
                gx, gy = world_to_grid(candidate)
                if NAV_GRID[gy, gx] == 0:
                    clear = all(
                        np.linalg.norm(candidate - other_pos) >= AGV_SAFETY_RADIUS
                        for oid, other_pos in reserved.items() if oid != agv.agv_id
                    )
                    if clear:
                        # Conectar el desvío y el destino final por la cuadrícula.
                        # Insertar un punto aislado producía atajos a través del rack.
                        candidate = grid_to_world((gx, gy))
                        outbound = find_path_grid(agv.pos, candidate, NAV_GRID)
                        inbound = find_path_grid(candidate, agv.path[-1], NAV_GRID)
                        route = outbound + inbound
                        points = [agv.pos] + route
                        if not all(segment_clear_of_obstacles(a, b) for a, b in zip(points, points[1:])):
                            continue
                        agv.path = route
                        self.mission_manager.log.append(f"[MANIOBRA] {agv.agv_id} se desvía para evitar bloqueo")
                        return True
        return False

    def _move_with_collision_avoidance(self, agv, reserved):
        if not agv.path:
            agv.stuck_steps = 0
            return

        original_speed = agv.speed
        for fraction in (1.0, 0.5, 0.25):
            agv.speed = original_speed * fraction
            next_pos = agv.peek_next_position()
            blocked = not segment_clear_of_obstacles(agv.pos, next_pos)
            for other_id, other_pos in reserved.items():
                if other_id == agv.agv_id:
                    continue
                if np.linalg.norm(next_pos - other_pos) < AGV_SAFETY_RADIUS:
                    blocked = True
                    break
            if not blocked:
                for ped in self.pedestrians:
                    movement = next_pos - agv.pos
                    length_sq = float(np.dot(movement, movement))
                    alpha = 0.0 if length_sq < 1e-9 else float(np.clip(np.dot(ped["pos"] - agv.pos, movement) / length_sq, 0, 1))
                    if np.linalg.norm(agv.pos + movement * alpha - ped["pos"]) < PEDESTRIAN_RADIUS:
                        blocked = True
                        break
            if not blocked:
                agv.follow_path()
                agv.speed = original_speed
                agv.stuck_steps = 0
                reserved[agv.agv_id] = agv.pos.copy()
                return

        agv.speed = original_speed
        agv.stuck_steps += 1

        if agv.stuck_steps >= DEADLOCK_THRESHOLD:
            if self._resolve_deadlock(agv, reserved):
                agv.stuck_steps = 0
            agv.speed = original_speed

    def step(self):
        # 1. Generación de misiones
        self.run_flow_generator()

        # 1b. Eventos dinamicos (peatones, alarmas de estacion)
        self.update_pedestrians()
        self.update_station_alarms()

        # 2. Subasta de misiones pendientes: el Mission Manager solo publica
        # y reune las pujas (tablon de anuncios); cada AGV decide por si mismo
        # si gano, viendo el mismo tablon (`determine_if_winner`), y se
        # autoasigna la mision (`accept_mission`). El Mission Manager nunca
        # compara AGVs ni elige un ganador.
        for m in self.mission_manager.missions.values():
            if m.status == MISSION_PENDING:
                self.mission_manager.publish_mission(m)
                bids = self.mission_manager.collect_bids(m, self.agvs)
                if not bids:
                    continue
                for agv in self.agvs:
                    if agv.determine_if_winner(bids):
                        agv.accept_mission(m)
                        m.status = MISSION_ASSIGNED
                        m.assigned_to = agv.agv_id
                        m.started_at = self.t
                        self.pallets[m.pallet_id].state = P_RESERVED
                        self.mission_manager.log.append(f"{agv.agv_id} gana la Misión {m.id}")
                        break

        # 3. Comportamiento y Movimiento de los AGVs

        # Posiciones ocupadas al inicio del paso
        reserved = {a.agv_id: a.pos.copy() for a in self.agvs}

        # Prioridad, primero quien va a cargar, luego menor bateria primero
        move_order = sorted(self.agvs, key=lambda a: (a.state != AGV_CHARGING, a.battery))

        for agv in move_order:
            # --- M4: conteo de pasos por estado (para utilizacion de la flota) ---
            if agv.state in (AGV_MOVING_TO_PALLET, AGV_TRANSPORTING):
                agv.active_steps += 1
            elif agv.state == AGV_CHARGING:
                agv.charging_steps += 1
            elif agv.state == AGV_IDLE:
                agv.idle_steps += 1

            # Transición a recarga
            if agv.state == AGV_IDLE and agv.battery <= LOW_BATTERY_THRESHOLD:
              if agv.go_to_recharge(self.chargers):
                  self.mission_manager.log.append(f"[BATERÍA] {agv.agv_id} ({agv.battery:.1f}%) se dirige a recargar")
              else:
                  self.mission_manager.log.append(f"[BATERÍA] {agv.agv_id} ({agv.battery:.1f}%) espera cargador libre")

            # Proceso de carga en estación
            elif agv.state == AGV_CHARGING:
              self._move_with_collision_avoidance(agv, reserved)
              if len(agv.path) == 0:
                  agv.battery = min(100.0, agv.battery + 4.0)
                  if agv.battery >= CHARGED_BATTERY_THRESHOLD:
                      agv.state = AGV_IDLE
                      if agv.charger is not None:
                          agv.charger["occupied_by"] = None
                          agv.charger = None
                      self.mission_manager.log.append(f"[BATERÍA] {agv.agv_id} recargado ({agv.battery:.1f}%), vuelve a IDLE")

            # Movimiento hacia el pallet
            elif agv.state == AGV_MOVING_TO_PALLET:
                pallet = self.pallets[agv.current_mission.pallet_id]
                self._move_with_collision_avoidance(agv, reserved)

                if len(agv.path) == 0:
                    agv.state = AGV_TRANSPORTING
                    pallet.state = P_BEING_TRANSPORTED
                    pallet.storage_zone = None
                    agv.path = find_path_grid(agv.pos, agv.current_mission.destination, NAV_GRID)

                    if agv.current_mission.origin_station_id is not None:
                        self.stations_by_name[agv.current_mission.origin_station_id].release()
                    else:
                        self.production_line.release_by_pallet(pallet.id)

                    self.mission_manager.log.append(f"[EVENTO] {agv.agv_id} recogió {pallet.id}")

            # Transporte hacia la zona de entrega
            elif agv.state == AGV_TRANSPORTING:
                pallet = self.pallets[agv.current_mission.pallet_id]
                self._move_with_collision_avoidance(agv, reserved)
                pallet.pos = agv.pos.copy()

                if len(agv.path) == 0:
                    agv.state = AGV_IDLE
                    agv.current_mission.status = MISSION_COMPLETED
                    agv.current_mission.completed_at = self.t
                    pallet.state = P_DELIVERED
                    pallet.storage_zone = agv.current_mission.dest_station_id
                    agv.completed_missions_count += 1
                    self.total_completed += 1

                    # La estacion de destino ahora tiene el pallet fisicamente
                    if agv.current_mission.dest_station_id is not None:
                        self.stations_by_name[agv.current_mission.dest_station_id].occupy(pallet.id)

                    self.mission_manager.log.append(f"[EVENTO] {agv.agv_id} entregó {pallet.id} ({agv.current_mission.id} completada)")
                    agv.current_mission = None

        self._record_frame()

"""# **Exportar a JSON (para Unity)**"""

def _to_serializable(obj):
    if isinstance(obj, np.ndarray):
        return [float(v) for v in obj]
    if isinstance(obj, dict):
        return {k: _to_serializable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_to_serializable(v) for v in obj]
    if isinstance(obj, (np.floating, np.integer)):
        return obj.item()
    if obj is None:
        # JsonUtility de Unity no soporta null en campos string: se usa "" en su lugar
        return ""
    return obj

def export_simulation(model, path="simulation_export.json"):
    """Vuelca la geometria estatica y el historial completo de la simulacion
    a un JSON para que Unity lo lea y reproduzca la animacion en 3D.

    Mapeo de coordenadas sugerido en Unity: world_x = sim.x * scale,
    world_z = sim.y * scale, world_y = altura fija (piso). Es decir, el
    plano (x, y) de esta simulacion 2D se convierte en el plano (x, z)
    de Unity (suelo), no en (x, y).
    """
    data = {
        "meta": {
            "width": WIDTH,
            "height": HEIGHT,
            "cell_size": CELL_SIZE,
            "agv_diameter": AGV_DIAMETER,
            "pallet_diameter": PALLET_DIAMETER,
            "pedestrian_radius": PEDESTRIAN_RADIUS,
            "agv_clearance": AGV_CLEARANCE,
            "navigation_obstacles": [z["name"] for z in zones_custom],
            "frame_sample": FRAME_SAMPLE,
            "n_agvs": model.p.n_agvs,
            "total_steps": model.p.steps,
            "total_completed": model.total_completed,
            "total_missions": model.mission_counter - 1,
        },
        "zones": _to_serializable(zones_custom),
        "chargers": [{"name": c["name"], "pos": _to_serializable(c["pos"])} for c in chargers_custom],
        "stations": [{"name": s["name"], "kind": s["kind"], "pos": _to_serializable(s["pos"])}
                     for s in STATION_DEFINITIONS],
        "frames": _to_serializable(model.history),
        "log": model.mission_manager.log,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Exportado a {path} ({len(model.history)} frames)")



def run_simulation(strategy, n_agvs=4, steps=800, seed=42, flow_scale=1.0):
    """Corre una simulación completa con la estrategia dada, controlando la
    semilla para que baseline y propuesta reciban las mismas condiciones
    (mismo layout, mismos AGVs, mismas misiones generadas por los flujos).
    `flow_scale=1.0` reproduce los intervalos de referencia del reto sin
    modificarlos; valores distintos solo se usan en el escenario experimental
    adicional de la sección "Escenario de mayor contención", mas abajo."""
    random.seed(seed)
    np.random.seed(seed)
    params = {'n_agvs': n_agvs, 'steps': steps, 'strategy': strategy, 'flow_scale': flow_scale}
    model = DistributionCenter(params)
    model.run(display=False)  # evita imprimir el progreso paso a paso en el notebook
    return model


if __name__ == "__main__":
    import argparse
    from pathlib import Path
    parser = argparse.ArgumentParser(description="Exporta M4 con todos sus pasos para Unity")
    parser.add_argument("--output", default=str(Path(__file__).resolve().parents[1] / "Assets/StreamingAssets/simulation_export.json"))
    parser.add_argument("--strategy", choices=[STRATEGY_BASELINE, STRATEGY_PROPOSED], default=STRATEGY_PROPOSED)
    parser.add_argument("--steps", type=int, default=800)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    model = run_simulation(args.strategy, steps=args.steps, seed=args.seed)
    export_simulation(model, args.output)
